@echo off
echo Starting Fund Evde PWA Development Server...
echo Activating Miniconda environment 'sports-pwa'...
call C:\Users\ABHIJITH\miniconda3\condabin\activate.bat sports-pwa
echo Starting the Vite server...
call npm run dev
pause
